workflows:
    android-workflow-id:
        name: Android Sample Workflow
        environment:
            flutter: stable
        # .......
    ios-workflow-id:
        name: iOS Sample Workflow
        environment:
            flutter: stable
        # .......
