workflows:
    android-workflow-id:
        name: Android Sample Workflow
        environment:
            flutter: non_existent_version
        # .......
    ios-workflow-id:
        name: iOS Sample Workflow
        environment:
            flutter: non_existent_version
        # .......
